# Generated by Django 5.0.6 on 2024-06-20 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('date_responded', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('Smartphone', 'Smartphone'), ('Tablet', 'Tablet'), ('Laptop', 'Laptop')], max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('date_received', models.DateField()),
                ('is_functional', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Refurbishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateField()),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('technician', models.CharField(max_length=100)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.device')),
            ],
        ),
        migrations.CreateModel(
            name='QualityAssurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_checked', models.DateField()),
                ('checked_by', models.CharField(max_length=100)),
                ('is_approved', models.BooleanField(default=False)),
                ('notes', models.TextField()),
                ('refurbishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.refurbishment')),
            ],
        ),
    ]
