# Generated by Django 5.0.6 on 2024-06-28 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_uploadedfile_usersession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_question_1', models.CharField(choices=[('What was your childhood nickname?', 'What was your childhood nickname?'), ('What is the name of your favorite childhood friend?', 'What is the name of your favorite childhood friend?'), ('What was your dream job as a child?', 'What was your dream job as a child?'), ('What is the name of your first pet?', 'What is the name of your first pet?'), ('What was the model of your first car?', 'What was the model of your first car?'), ('What elementary school did you attend?', 'What elementary school did you attend?')], max_length=255)),
                ('security_answer_1', models.CharField(max_length=255)),
                ('security_question_2', models.CharField(choices=[('What was your childhood nickname?', 'What was your childhood nickname?'), ('What is the name of your favorite childhood friend?', 'What is the name of your favorite childhood friend?'), ('What was your dream job as a child?', 'What was your dream job as a child?'), ('What is the name of your first pet?', 'What is the name of your first pet?'), ('What was the model of your first car?', 'What was the model of your first car?'), ('What elementary school did you attend?', 'What elementary school did you attend?')], max_length=255)),
                ('security_answer_2', models.CharField(max_length=255)),
                ('security_question_3', models.CharField(choices=[('What was your childhood nickname?', 'What was your childhood nickname?'), ('What is the name of your favorite childhood friend?', 'What is the name of your favorite childhood friend?'), ('What was your dream job as a child?', 'What was your dream job as a child?'), ('What is the name of your first pet?', 'What is the name of your first pet?'), ('What was the model of your first car?', 'What was the model of your first car?'), ('What elementary school did you attend?', 'What elementary school did you attend?')], max_length=255)),
                ('security_answer_3', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
